[package]
org = "ballerina"
name = "time"
version = "2.2.4"
authors = ["Ballerina"]
keywords = ["time", "utc", "epoch", "civil"]
repository = "https://github.com/ballerina-platform/module-ballerina-time"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.0.4"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "time-native"
version = "2.2.4"
path = "../native/build/libs/time-native-2.2.4-SNAPSHOT.jar"
